#!/bin/bash
set -eu
npx now deploy --prod \
-e NODE_ENV=production \
-e PASSWORD_SHA1=$PASSWORD_SHA1 \
-e PLAID_CLIENT_ID=$PLAID_CLIENT_ID \
-e PLAID_SECRET=$PLAID_SECRET \
-e PLAID_PUBLIC_KEY=$PLAID_PUBLIC_KEY \
-e PLAID_ENV=$PLAID_ENV \
-e FIREBASE_SERVICE_ACCOUNT=$FIREBASE_SERVICE_ACCOUNT \
-e FIREBASE_DB_URL=$FIREBASE_DB_URL \
"$@"
